id: IA1FC7AEF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T06:26:03+00:00'
last_modified: '2022-06-08T13:04:22.494747+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20275
  title: མཚོ་ལྷོ་བོད་རིགས་རང་སྐྱོང་ཁུལ་གྱི་རི་ཆུའི་རིག་གནས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    66B6:
      image_group_id: I8LS20277
      title: Volume 1 of mtsho lho bod rigs rang skyong khul gyi ri chu'i rig gnas/
      total_pages: 776
      order: 1
      base_file: 66B6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
