id: P006966
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20275
  title: མཚོ་ལྷོ་བོད་རིགས་རང་སྐྱོང་ཁུལ་གྱི་རི་ཆུའི་རིག་གནས།
  author: ''
  volumes:
    522f991475684a2097a82803d1aba552:
      image_group_id: I8LS20277
      title: ''
      volume_number: 1
      total_pages: 776
ebook_metadata:
  title: མཚོ་ལྷོ་བོད་རིགས་རང་སྐྱོང་ཁུལ་གྱི་རི་ཆུའི་རིག་གནས།
  author: ''
  sku: P006966
  cover: cover.jpg
  layers:
  - pagination
